// <auto-generated />
using System;
using CommonDatabase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommonDatabase.Migrations
{
    [DbContext(typeof(BetfairDataContext))]
    [Migration("20220429010358_added-odd-date")]
    partial class addedodddate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CommonDatabase.Entities.Odd", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EmpateOuVisitante")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaisDe2_5Gols")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MenosDe2_5Gols")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NomeTimeCasa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomeTimeVisitante")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PontuacaoCorretaEmpate_1_0")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PontuacaoCorretaEmpate_2_0")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PontuacaoCorretaEmpate_2_1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PontuacaoCorretaTimeCasa_1_0")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PontuacaoCorretaTimeCasa_2_0")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PontuacaoCorretaTimeCasa_2_1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PontuacaoCorretaTimeVisitante_1_0")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PontuacaoCorretaTimeVisitante_2_0")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PontuacaoCorretaTimeVisitante_2_1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProbabilidadeEmpate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProbabilidadeVitoriaTimeCasa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProbabilidadeVitoriaTimeVisitante")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("TipoEvento")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Total0Gols")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total1Gols")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total2Gols")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total3Gols")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total4Gols")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VisitadoOuEmpate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VisitadoOuVisitante")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Odd");
                });

            modelBuilder.Entity("CommonDatabase.Entities.Resultado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("Horario")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeTimeCasa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomeTimeVisitante")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("PontuacaoTimeCasa")
                        .HasColumnType("smallint");

                    b.Property<short>("PontuacaoTimeVisitante")
                        .HasColumnType("smallint");

                    b.Property<byte>("TipoEvento")
                        .HasColumnType("tinyint");

                    b.Property<short>("TotalGols")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Resultado");
                });
#pragma warning restore 612, 618
        }
    }
}
